
/**
 * Author: Jonas Okwara
 * Date: 05-16-18,
 * updated 05-31-18
 * Class that implements contracts
 * stipulated by IScanUtility class
 */

package hcqis.cloud.automation.model.utility.scanutility;

import java.io.IOException;
import java.util.logging.Logger;


public class ScanUtility implements IScanUtility {
	Logger logger = Logger.getLogger("ScanUtility");


	
	/**
	 * @Author: Jonas Okwara
	 * @Date: 05-16-18 
	 * Call the Openscap scan command and perform a scan on a
	 * host and send the status update.
	 * @return String
	 */
	public String performHostScan(String nodeName) {
		
		String exitMessage = null; 
		Process OSCmdProcess = null;
		
		
		
		String OScmd = new String("/usr/bin/ssh  oscapscn@"+nodeName + " " + "/home/oscapscn/openscap.bash");	
			
		logger.info(OScmd);
			
		try {
			OSCmdProcess = Runtime.getRuntime().exec(OScmd); 
			 OSCmdProcess.waitFor();  
			 			
			 
			int  exitStatus =   OSCmdProcess.exitValue();
			
			logger.info("The Exit Value is:" + exitStatus);
			
			if (exitStatus != 0) {
				
				exitMessage = ("Scan Failed:" + "-"+ nodeName);
	
			} else {
				
				exitMessage = ("Scan Succeeded:" + "-" + nodeName);
	
			}
		} catch (IOException ioExcep) {
			ioExcep.printStackTrace();
		} catch (InterruptedException interExcep) {
			interExcep.printStackTrace();
		} 
		return exitMessage;

	}   
		
	/**
	 * Author Jonas  Okwara
	 * Date 06-14-2018
	 * method that retrieves html
	 * reports generated by openscap scan
	 * @param nodeName
	 *   
	 *
	private  void retrieveReports(String nodeName) {  
		
	  //String OScmd = new String("/usr/bin/sudo"+ " " +"/usr/bin/scp ansible@" + nodeName + ":" + "/home/ansible/*.html   /tmp/myDump"); 
		Process OSCmdProcess = null;
		
	   String OScmd = new String("/bin/bash"  + " " + "/home/oscapscn/getThemAll.bash" + " " + nodeName);
		logger.info(OScmd);
	  
	  try{
		  OSCmdProcess = Runtime.getRuntime().exec(OScmd);  
		  int exitValue = OSCmdProcess.waitFor();
	  }catch(IOException | InterruptedException IOExcep){
		  IOExcep.printStackTrace();
		  
	  }
	  }
	  **/
	
	/**
	 * 
	 * @param args
	 *
	public static void main(String[]args) {
		new ScanUtility().retrieveReports("owl");
	}
   */

}
