<%@ include file="/includes/homeHeader.jsp"%> 
<body>
<div id="wrapper">
<div id="banner"> <h6>OpenScap Automation Tool</h6> </div>
<nav class="navbar navbar-inverse">
<div class="container-fluid"> 

<ul class="nav navbar-nav navbar-left">
<li><a href="initial.jsp"><span class="glyphicon glyphicon-home"></span>Home</a></li>  
<li><a href="scanGui.jsp"><span class="glyphicon glyphicon-user"></span>Real Time Scan</a></li>
<li><a href="scanActivity.jsp"><span class="glyphicon glyphicon-user"></span>Scan Activity Details</a></li> 
<li><a href="schedulerGui.jsp"><span class="glyphicon glyphicon-log-in"></span>Scheduler</a></li> 
<li><a href="reportGui.jsp"><span class="glyphicon glyphicon-user"></span>Scan Reports</a></li>
</ul>


<ul class="nav navbar-nav navbar-right logout">
<li><a href="initial.jsp"><h1>${sessionMessage} ${userObj.firstname} ${userObj.lastname}<span style="margin-left: 14px"> LogOut</span></h1></a></li>
</ul>
</div>
</nav>
<!-- End of Banner and Headers -->   

 
<div class="panel panel-info content-panel">
<div class="panel panel-heading">hello </div>
<div class="panel panel-body">  

<div class="imagesContainer">

<div class="row 1stRow">  <!--Start Of First Row Column -->  

<div class="col-md-4  firstColumn"> <!-- Start of First Column -->
<div class="panel panel-info">

<div class="panel panel-body">  

<div class="imgBox1">
<img
style="width: 220px; height: 200px; margin-top: 2px; margin-left:auto; margin-right: auto; margin-bottom: 20px; border: 2px solid #9CC"
src="images/curious.jpeg" class="img-rounded"
alt="Cinque Terre" />
</div>

<div class="txtBox1">
<span class="center-block" style="text-align:left">

<h8>Run A Compliance Scan </h8>
<br>
<a href="scanGui.jsp"> 
<p>
choose any number of hosts and run a 
compliance scan anytime of the day.
</p>
</a>
</span>
</div>

</div>
</div>
</div><!-- End First Column -->

<div class="col-md-4 secondColumn"><!-- Start of Second Column -->  
<div class="panel panel-info">

<div class="panel panel-body">  

<div class="imgBox2">
<img
style="width: 220px; height: 200px; margin-top: 2px; margin-left:auto; margin-right: auto; margin-bottom: 20px; border: 2px solid #9CC"
src="images/parrots.jpeg" class="img-rounded"
alt="Cinque Terre" />

</div>



<div class="txtBox2">

<h8>Schedule A  Scan </h8>
<br>

<a href="schedulerGui.jsp">
Schedule Scan to run at any 
Calendar day and time of your
own choosing. 
</a>
</div>


</div>
</div>
</div><!-- End Second Column -->

<div class="col-md-4 thirdColumn"><!-- Start of Third Column --> 
<div class="panel panel-info">

<div class="panel panel-body">  

<div class="imgBox3">
<img
style="width: 220px; height: 200px; margin-top: 2px; margin-left:auto; margin-right: auto; margin-bottom: 20px; border: 2px solid #9CC"
src="images/unique.jpeg" class="img-rounded"
alt="Cinque Terre" />

</div>

<div class="txtBox3">
<h8>View Generated Reports </h8>
<br>
<a href="reportGui.jsp">
View reports generated by a compliance scan on the 
respective hosts
</a>
</div>
</div>
</div>
</div>
</div>
</div><!-- End Third Column -->
</div><!-- End Of First Row Column -->  










</div>


</div>

<!-- End of Content Wrapper -->
</body>
</html>